apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: sdo-backend:latest
        imagePullPolicy: Never # Remove if using external registry like GHCR
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: sdo-config
        - secretRef:
            name: sdo-secrets

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
